- name: Ruby | Checks if target ruby is installed
  action: shell cd; bash -lc "rbenv versions | grep {{ version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '"
  register: ruby_is_installed
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Installs ruby
  action: shell cd; bash -lc "rbenv install {{ version }}"
  when: ruby_is_installed is not defined 
  # Takes no more than 600 secs on a small VM
  async: 600
  poll: 30
  tags:
    - ruby
    - ruby:install
    - install

